### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by cfhammill** [cfhammill/lenses#8]
Submission in progress. Auto checks all passed. Waiting on manual review

**Comment by cfhammill** [comment]
Fortunately we have been rejected. Uwe wants us to fix up the description and add a bit more explanation. This is fortunate because we can now change the name in time for first release

**Comment by cfhammill** [comment]
Yet another rejection, this time for slightly more substantive reasons. Uwe has requested that we:

- [ ] Single quote software names, e.g. haskell, further suggesting we capitalize the H.
- [ ] Provide paper references or websites in the description. This should be fine, we'll just include Jules' blog and a link to the lens package.
- [ ] Provide more code examples in our docs.

Obviously number three is the most serious. But a reasonable request. 

I think we're fortunate again here, our first release will have `map_l` which is kind of necessary.

**Comment by cfhammill** [comment]
A few more docs needed, finished all base-lenses.R (except unlist_l), all array-lenses.R, all dataframe-lenses.R (except transpose_l), all lens.R (except oscope but not bothering there). Remains to be done, verbs.R and text-lenses.R

**Comment by cfhammill** [comment]
@bcdarwin Any outstanding (high-priority) issues before resubmission?

**Comment by bcdarwin** [comment]
Nothing on my end ... what about `version %>% over(last_l, x ~ x + 1)` ?
